/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import BusinessLayer.UsuarioBO;
import JavaBean.Usuario;
import Utilities.Validator;
import java.util.Map;

/**
 *
 * @author black
 */
public class InsertUsuario extends javax.swing.JFrame {

    /**
     * Creates new form InsertUsuario
     */
    public InsertUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBRegistrar = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        lbNombreUsuario = new javax.swing.JLabel();
        lbApellidoPaternoUsuario = new javax.swing.JLabel();
        lbDNIUsuario = new javax.swing.JLabel();
        txtNombresUsuario = new javax.swing.JTextField();
        txtApellidoPaternoUsuario = new javax.swing.JTextField();
        txtApellidoMaternoUsuario = new javax.swing.JTextField();
        lbApellidoMaternoUsuario = new javax.swing.JLabel();
        lbRolUsuario = new javax.swing.JLabel();
        txtDNIUsuario = new javax.swing.JTextField();
        txtClaveUsuario = new javax.swing.JTextField();
        lbClaveUsuario = new javax.swing.JLabel();
        txtRolUsuario = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        NombreError = new javax.swing.JLabel();
        APaternoError = new javax.swing.JLabel();
        AMaternoError = new javax.swing.JLabel();
        DNIError = new javax.swing.JLabel();
        ClaveError = new javax.swing.JLabel();
        RolError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(430, 480));
        setResizable(false);

        JBRegistrar.setText("Registrar");
        JBRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRegistrarActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("INSERTAR USUARIO");

        lbNombreUsuario.setText("Nombres :");

        lbApellidoPaternoUsuario.setText("Apellido paterno :");

        lbDNIUsuario.setText("DNI :");

        lbApellidoMaternoUsuario.setText("Apellido materno :");

        lbRolUsuario.setText("Rol : ");

        txtClaveUsuario.setMaximumSize(new java.awt.Dimension(80, 2147483647));

        lbClaveUsuario.setText("Clave :");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        NombreError.setForeground(new java.awt.Color(255, 0, 0));

        APaternoError.setForeground(new java.awt.Color(255, 0, 0));

        AMaternoError.setForeground(new java.awt.Color(255, 0, 0));

        DNIError.setForeground(new java.awt.Color(255, 0, 0));

        ClaveError.setForeground(new java.awt.Color(255, 0, 0));

        RolError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbNombreUsuario)
                        .addGap(66, 66, 66)
                        .addComponent(txtNombresUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(NombreError, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbApellidoPaternoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellidoPaternoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(APaternoError, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbApellidoMaternoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellidoMaternoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(AMaternoError, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbDNIUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(txtDNIUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(DNIError, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbClaveUsuario)
                        .addGap(86, 86, 86)
                        .addComponent(txtClaveUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(ClaveError, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbRolUsuario)
                        .addGap(94, 94, 94)
                        .addComponent(txtRolUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(RolError, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(JBRegistrar)
                        .addGap(47, 47, 47)
                        .addComponent(btnCancelar)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNombreUsuario)
                    .addComponent(txtNombresUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(NombreError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbApellidoPaternoUsuario)
                    .addComponent(txtApellidoPaternoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(APaternoError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbApellidoMaternoUsuario)
                    .addComponent(txtApellidoMaternoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(AMaternoError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDNIUsuario)
                    .addComponent(txtDNIUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(DNIError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbClaveUsuario)
                    .addComponent(txtClaveUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(ClaveError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRolUsuario)
                    .addComponent(txtRolUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(RolError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(JBRegistrar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void JBRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRegistrarActionPerformed
        // TODO add your handling code here:
        String nombres = txtNombresUsuario.getText();
        String apellidopaterno = txtApellidoPaternoUsuario.getText();
        String apellidomaterno = txtApellidoMaternoUsuario.getText();
        String dni = txtDNIUsuario.getText();
        String clave = txtClaveUsuario.getText();
        String rol = txtRolUsuario.getText();
        UsuarioBO ubo = new UsuarioBO();
        Usuario usuario = new Usuario();
        usuario.setNombres(nombres);
        usuario.setApellido_paterno(apellidopaterno);
        usuario.setApellido_materno(apellidomaterno);
        try {
            usuario.setDni(dni);
        } catch (Exception ex) {
            System.out.println(ex);
        }
        usuario.setClave(clave);
        usuario.setRol(rol);
        LimpiarErrores();
        System.out.println("P1");
        if(nombres.isBlank() || apellidopaterno.isBlank() || apellidomaterno.isBlank() || dni.isBlank() || clave.isBlank() || rol.isBlank()){
            System.out.println(usuario.getErrores().isEmpty());
            if(!usuario.getErrores().isEmpty()){
                ImprimirErrores(usuario.getErrores());
            }
            System.out.println("P1-entro");
        }else{
            System.out.println("P2");
            if(Validator.isDNI(dni) && clave.length()>=8){
                System.out.println("P2-entro1");
                try {
                    ubo.insertar(usuario);
                    dispose();
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            }else{
                System.out.println("Entro error");
                if(!Validator.isDNI(dni)){
                    DNIError.setText("Ingrese un DNI valido");
                }
                if(clave.length()<8){
                    ClaveError.setText("La clave debe ser minimo de 8 caracteres");
                }
            }
        }
    }//GEN-LAST:event_JBRegistrarActionPerformed

    
    private void ImprimirErrores(Map<String, String> errores){    
        for (String error : errores.keySet().toArray(new String[0])) {
            System.out.println(errores.get(error));
            switch (error) {
                case "nombres" -> NombreError.setText(errores.get(error));
                case "apellido_paterno" -> APaternoError.setText(errores.get(error));
                case "apellido_materno" -> AMaternoError.setText(errores.get(error));
                case "dni" -> DNIError.setText(errores.get(error));
                case "claveLen" -> ClaveError.setText(errores.get(error));
                case "clave" -> ClaveError.setText(errores.get(error));
                case "rol" -> RolError.setText(errores.get(error));
            }
            System.out.println(error);
        }
    }
    
    private void LimpiarErrores(){
        NombreError.setText("");
        APaternoError.setText("");
        AMaternoError.setText("");
        DNIError.setText("");
        ClaveError.setText("");
        RolError.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AMaternoError;
    private javax.swing.JLabel APaternoError;
    private javax.swing.JLabel ClaveError;
    private javax.swing.JLabel DNIError;
    private javax.swing.JButton JBRegistrar;
    private javax.swing.JLabel NombreError;
    private javax.swing.JLabel RolError;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lbApellidoMaternoUsuario;
    private javax.swing.JLabel lbApellidoPaternoUsuario;
    private javax.swing.JLabel lbClaveUsuario;
    private javax.swing.JLabel lbDNIUsuario;
    private javax.swing.JLabel lbNombreUsuario;
    private javax.swing.JLabel lbRolUsuario;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtApellidoMaternoUsuario;
    private javax.swing.JTextField txtApellidoPaternoUsuario;
    private javax.swing.JTextField txtClaveUsuario;
    private javax.swing.JTextField txtDNIUsuario;
    private javax.swing.JTextField txtNombresUsuario;
    private javax.swing.JTextField txtRolUsuario;
    // End of variables declaration//GEN-END:variables
}
