/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import BusinessLayer.AlumnoApoderadoBO;
import BusinessLayer.AlumnoBO;
import BusinessLayer.ApoderadoBO;
import JavaBean.Alumno;
import JavaBean.Apoderado;
import JavaBean.alumnoApoderado;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author black
 */
public class PruebaApoderado extends javax.swing.JFrame {

    /**
     * Creates new form PruebaApoderado
     */
    public PruebaApoderado() {
        initComponents();
        try {
            alumnos = alumBO.buscarPorAlumno("");
            apoderados = apoBO.buscarApoderadoPorNombre("");
            alumnoApoderados = alumnoApoderadoBO.listar();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        actualizarTablaAlumno();
        actualizarTablaApoderado();
        actualizarTablaAlumnoApoderado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTableAlumnoApoderado = new javax.swing.JTable();
        btnBuscarAlumno = new javax.swing.JButton();
        JTextAlumnoNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JTextBuscarNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextAlumnoId = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableGestionAlumno = new javax.swing.JTable();
        btnInsertar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JTextBuscarNombre1 = new javax.swing.JTextField();
        btnBuscarAlumno2 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableGestionApoderado = new javax.swing.JTable();
        JTextApoderadoNombre = new javax.swing.JTextField();
        jTextApoderadoId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextParentesco = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jTextActualizarAlumno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextActualizarApoderado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableAlumnoApoderado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Alumno_id", "DNI", "Apellidos y Nombres", "Ape. y Nom. apoderado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAlumnoApoderado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAlumnoApoderadoMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableAlumnoApoderado);

        btnBuscarAlumno.setText("Buscar");
        btnBuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlumnoActionPerformed(evt);
            }
        });

        JTextAlumnoNombre.setEnabled(false);
        JTextAlumnoNombre.setMaximumSize(new java.awt.Dimension(250, 22));
        JTextAlumnoNombre.setMinimumSize(new java.awt.Dimension(250, 22));
        JTextAlumnoNombre.setName(""); // NOI18N
        JTextAlumnoNombre.setPreferredSize(new java.awt.Dimension(250, 22));

        jLabel1.setText("Alumno:");

        jLabel2.setText("Nombres:");

        jLabel9.setText("CODIGO ALUMNO:");

        jTextAlumnoId.setEnabled(false);
        jTextAlumnoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAlumnoIdActionPerformed(evt);
            }
        });

        jTableGestionAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Alumno_id", "DNI", "Apellidos y Nombres"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableGestionAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGestionAlumnoMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTableGestionAlumno);

        btnInsertar.setText("Insertar relacion");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombres:");

        btnBuscarAlumno2.setText("Buscar");
        btnBuscarAlumno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlumno2ActionPerformed(evt);
            }
        });

        jTableGestionApoderado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Alumno_id", "DNI", "Apellidos y Nombres"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableGestionApoderado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGestionApoderadoMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jTableGestionApoderado);

        JTextApoderadoNombre.setEnabled(false);
        JTextApoderadoNombre.setMaximumSize(new java.awt.Dimension(250, 22));
        JTextApoderadoNombre.setMinimumSize(new java.awt.Dimension(250, 22));
        JTextApoderadoNombre.setName(""); // NOI18N
        JTextApoderadoNombre.setPreferredSize(new java.awt.Dimension(250, 22));

        jTextApoderadoId.setEnabled(false);
        jTextApoderadoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextApoderadoIdActionPerformed(evt);
            }
        });

        jLabel10.setText("CODIGO APODERADO:");

        jLabel4.setText("Apoderado");

        jLabel5.setText("Alumno_id:");

        btnEliminar.setText("Eliminar relacion");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar relacion");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jTextActualizarAlumno.setEnabled(false);

        jLabel6.setText("Apoderado_id:");

        jLabel7.setText("Parentesco:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarAlumno)
                        .addGap(136, 136, 136))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jTextAlumnoId))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(74, 74, 74)
                                .addComponent(JTextAlumnoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTextBuscarNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarAlumno2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jTextApoderadoId))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(74, 74, 74)
                                .addComponent(JTextApoderadoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnInsertar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnActualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextActualizarApoderado, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextActualizarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextAlumnoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(JTextAlumnoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(JTextBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarAlumno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextApoderadoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(JTextApoderadoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(JTextBuscarNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarAlumno2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(49, 49, 49)
                        .addComponent(btnInsertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizar)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextActualizarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextActualizarApoderado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoActionPerformed
        try {
            alumnos = alumBO.buscarPorAlumno(JTextBuscarNombre.getText());
            actualizarTablaAlumno();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarAlumnoActionPerformed

    private void jTextAlumnoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAlumnoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAlumnoIdActionPerformed

    private void jTableGestionAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGestionAlumnoMouseClicked
        // TODO add your handling code here:
        int fila = jTableGestionAlumno.getSelectedRow();

        if(fila !=-1){
            JTextAlumnoNombre.setText((String) jTableGestionAlumno.getValueAt(fila, 1));
            jTextAlumnoId.setText(jTableGestionAlumno.getValueAt(fila, 0).toString());
//            jbPrincipal.setEnabled(true);
        }
    }//GEN-LAST:event_jTableGestionAlumnoMouseClicked

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        alumnoApoderado alumApo = new alumnoApoderado();
        
        alumApo.setParentesco(jTextParentesco.getText());
        alumApo.setAlumno_id(Integer.parseInt(jTextAlumnoId.getText()));
        alumApo.setApoderado_id(Integer.parseInt(jTextApoderadoId.getText()));
        
        try {
            alumnoApoderadoBO.insertar(alumApo);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        
        try {
            alumnoApoderados = alumnoApoderadoBO.listar();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        
        actualizarTablaAlumnoApoderado();
        
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnBuscarAlumno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlumno2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarAlumno2ActionPerformed

    private void jTableGestionApoderadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGestionApoderadoMouseClicked
        // TODO add your handling code here:
        int fila = jTableGestionApoderado.getSelectedRow();

        if(fila !=-1){
            JTextApoderadoNombre.setText((String) jTableGestionApoderado.getValueAt(fila, 1));
            jTextApoderadoId.setText(jTableGestionApoderado.getValueAt(fila, 0).toString());
//            jbPrincipal.setEnabled(true);
        }
    }//GEN-LAST:event_jTableGestionApoderadoMouseClicked

    private void jTextApoderadoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextApoderadoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextApoderadoIdActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = jTableAlumnoApoderado.getSelectedRow();

        try {
            System.out.println( "Eliminando AlumnoApoderado con id: "+jTableAlumnoApoderado.getValueAt(fila, 1) );
            int alumno_id = (int) jTableAlumnoApoderado.getValueAt(fila, 0);
            int apoderado_id = (int) jTableAlumnoApoderado.getValueAt(fila, 1);
            System.out.println("Alumno ID :"+alumno_id+ ", Apoderado ID :"+apoderado_id);
            alumnoApoderadoBO.eliminar(alumno_id , apoderado_id);
            
            modeloAlumnoApoderado.removeRow(fila);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        alumnoApoderado alumApo = new alumnoApoderado();
        
        alumApo.setParentesco(jTextParentesco.getText());
        alumApo.setAlumno_id(Integer.parseInt(jTextActualizarAlumno.getText()));
        alumApo.setApoderado_id(Integer.parseInt(jTextActualizarApoderado.getText()));
        
        try {
            alumnoApoderadoBO.actualizar(alumApo);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        
        try {
            alumnoApoderados = alumnoApoderadoBO.listar();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        
        actualizarTablaAlumnoApoderado();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jTableAlumnoApoderadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAlumnoApoderadoMouseClicked
        // TODO add your handling code here:
        int fila = jTableAlumnoApoderado.getSelectedRow();

        if(fila !=-1){
            jTextActualizarAlumno.setText(jTableAlumnoApoderado.getValueAt(fila, 0).toString());
            jTextActualizarApoderado.setText(jTableAlumnoApoderado.getValueAt(fila, 1).toString());
            jTextParentesco.setText(jTableAlumnoApoderado.getValueAt(fila, 2).toString());
//            jbPrincipal.setEnabled(true);
        }
    }//GEN-LAST:event_jTableAlumnoApoderadoMouseClicked

    /**
     * @param args the command line arguments
     */
    private DefaultTableModel modeloAlumnoApoderado;
    private ArrayList<alumnoApoderado> alumnoApoderados;
    private AlumnoApoderadoBO alumnoApoderadoBO = new AlumnoApoderadoBO();
    
    private void actualizarTablaAlumnoApoderado() {
        modeloAlumnoApoderado = new DefaultTableModel();

        jTableAlumnoApoderado.setModel(modeloAlumnoApoderado);

        modeloAlumnoApoderado.addColumn("alum_id");
        modeloAlumnoApoderado.addColumn("apoderado_id");
        modeloAlumnoApoderado.addColumn("parentesco");
        
        try {
            for (int i = 0; i < alumnoApoderados.size(); i++) {
                alumnoApoderado alumApo = alumnoApoderados.get(i);
//                String apellidosNombres = apoderado.getApellido_paterno() + " " + apoderado.getApellido_materno() + " , " + apoderado.getNombres();

                Object[] fila = new Object[]{alumApo.getAlumno_id(),alumApo.getApoderado_id(),
                alumApo.getParentesco()};
                modeloAlumnoApoderado.addRow(fila);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private DefaultTableModel modeloApoderado;
    private ArrayList<Apoderado> apoderados;
    private ApoderadoBO apoBO = new ApoderadoBO();

    private void actualizarTablaApoderado() {
        modeloApoderado = new DefaultTableModel();

        jTableGestionApoderado.setModel(modeloApoderado);

        modeloApoderado.addColumn("apoderado_id");
        modeloApoderado.addColumn("apellido_nombres");
        modeloApoderado.addColumn("dni");
        
        try {
            for (int i = 0; i < apoderados.size(); i++) {
                Apoderado apoderado = apoderados.get(i);
                String apellidosNombres = apoderado.getApellido_paterno() + " " + apoderado.getApellido_materno() + " , " + apoderado.getNombres();

                Object[] fila = new Object[]{apoderado.getApoderado_id(),apellidosNombres,
                apoderado.getDni()};
                modeloApoderado.addRow(fila);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private DefaultTableModel modeloAlumnos;
    private AlumnoBO alumBO = new AlumnoBO();
    private ArrayList<Alumno> alumnos;

    private void actualizarTablaAlumno() {
        modeloAlumnos = new DefaultTableModel();

        jTableGestionAlumno.setModel(modeloAlumnos);

        modeloAlumnos.addColumn("Alumno id");
        modeloAlumnos.addColumn("Apellidos y Nombres");
        modeloAlumnos.addColumn("DNI");

        try {
            System.out.println(alumnos.size());
            for (int i = 0; i < alumnos.size(); i++) {
                Alumno alumno = alumnos.get(i);
                String apellidosNombres = alumno.getApellido_paterno() + " " + alumno.getApellido_materno() + " , " + alumno.getNombres();

                Object[] fila = new Object[]{alumno.getAlumno_id(), apellidosNombres,
                alumno.getDni()};
                modeloAlumnos.addRow(fila);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaApoderado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaApoderado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaApoderado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaApoderado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaApoderado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextAlumnoNombre;
    private javax.swing.JTextField JTextApoderadoNombre;
    private javax.swing.JTextField JTextBuscarNombre;
    private javax.swing.JTextField JTextBuscarNombre1;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscarAlumno;
    private javax.swing.JButton btnBuscarAlumno2;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTableAlumnoApoderado;
    private javax.swing.JTable jTableGestionAlumno;
    private javax.swing.JTable jTableGestionApoderado;
    private javax.swing.JTextField jTextActualizarAlumno;
    private javax.swing.JTextField jTextActualizarApoderado;
    private javax.swing.JTextField jTextAlumnoId;
    private javax.swing.JTextField jTextApoderadoId;
    private javax.swing.JTextField jTextParentesco;
    // End of variables declaration//GEN-END:variables
}
