/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import BusinessLayer.ApoderadoBO;
import DataAccessLayer.ApoderadoDAO;
import JavaBean.Apoderado;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author black
 */
public class VentanaApoderado extends javax.swing.JFrame {

    /**
     * Creates new form InsertApoderado
     * @param apoderado
     */
    public VentanaApoderado(Apoderado apoderado) {
        initComponents();
        jlTitulo.setText("Actualizar Apoderado: ");
        jlID.setText(String.valueOf(apoderado.getApoderado_id()));
        jbPrincipal.setText("Actualizar");
                
        //Se completa el formulario
        jTextDni.setText(apoderado.getDni());
        jTextApellidoPaterno.setText(apoderado.getApellido_paterno());
        jTextApellidoMaterno.setText(apoderado.getApellido_materno());
        jTextNombres.setText(apoderado.getNombres());
        jTextContacto.setText(apoderado.getContacto());
    }
    
    public VentanaApoderado() {
        initComponents();
        jlTitulo.setText("Insertar");
        jlID.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextDni = new javax.swing.JTextField();
        jTextApellidoMaterno = new javax.swing.JTextField();
        jTextApellidoPaterno = new javax.swing.JTextField();
        jTextNombres = new javax.swing.JTextField();
        jTextContacto = new javax.swing.JTextField();
        jLabelDni = new javax.swing.JLabel();
        jLabelApellidoPaterno = new javax.swing.JLabel();
        jLabelApellidoMaterno = new javax.swing.JLabel();
        jLabelNombres = new javax.swing.JLabel();
        jLabelContacto = new javax.swing.JLabel();
        jlID = new javax.swing.JLabel();
        jbPrincipal = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlTitulo.setText("Actualizar Apoderado: ");

        jLabel2.setText("Nombres:");

        jLabel3.setText("Apellido materno:");

        jLabel4.setText("Apellido paterno:");

        jLabel5.setText("DNI :");

        jLabel6.setText("Contacto: ");

        jTextDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDniActionPerformed(evt);
            }
        });

        jLabelDni.setForeground(new java.awt.Color(255, 51, 51));
        jLabelDni.setText("-");

        jLabelApellidoPaterno.setForeground(new java.awt.Color(255, 51, 51));
        jLabelApellidoPaterno.setText("-");

        jLabelApellidoMaterno.setForeground(new java.awt.Color(255, 51, 51));
        jLabelApellidoMaterno.setText("-");

        jLabelNombres.setForeground(new java.awt.Color(255, 51, 51));
        jLabelNombres.setText("-");

        jLabelContacto.setForeground(new java.awt.Color(255, 51, 51));
        jLabelContacto.setText("-");

        jlID.setForeground(new java.awt.Color(51, 51, 255));
        jlID.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextDni, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextApellidoMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                .addComponent(jTextApellidoPaterno)
                                .addComponent(jTextNombres)
                                .addComponent(jTextContacto)
                                .addComponent(jLabelDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelApellidoPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelApellidoMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabelContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTitulo)
                    .addComponent(jlID))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(3, 3, 3)
                .addComponent(jLabelDni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(2, 2, 2)
                .addComponent(jLabelApellidoPaterno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(1, 1, 1)
                .addComponent(jLabelApellidoMaterno)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(3, 3, 3)
                .addComponent(jLabelNombres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbPrincipal.setText("Insertar");
        jbPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrincipalActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPrincipal)
                    .addComponent(jButton2))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDniActionPerformed

    private void jbPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrincipalActionPerformed
        Apoderado apoderado = recibirDatos();
        
        if(jbPrincipal.getText().equals("Insertar"))
            insertar(apoderado);
        
        else if(jbPrincipal.getText().equals("Actualizar"))
            actualizar(apoderado);
        
    }//GEN-LAST:event_jbPrincipalActionPerformed

    private Apoderado recibirDatos(){
        Apoderado apoderado = new Apoderado();
        
        apoderado.setNombres(jTextNombres.getText());
        apoderado.setApellido_paterno(jTextApellidoPaterno.getText());
        apoderado.setApellido_materno(jTextApellidoMaterno.getText());
        apoderado.setDni(jTextDni.getText());
        apoderado.setContacto(jTextContacto.getText());
        
        if(!jlID.getText().isEmpty())
            apoderado.setApoderado_id(Integer.parseInt(jlID.getText()));
        
        limpiarErrores();
        return apoderado;
    }
    
    private void insertar(Apoderado apoderado){
        ApoderadoBO apoBO = new ApoderadoBO();
        
        if(apoderado.getErrores().isEmpty()){
            try {
                apoBO.insertarApoderado(apoderado);
                dispose();
            } catch (Exception e) {
                if ( e.getMessage().contains("El DNI ingresado ya existe") ) {
                    jLabelDni.setText("El DNI ingresado ya fue registrado");
                }
                if ( e.getMessage().contains("El Contacto ingresado ya existe") ) {
                    jLabelContacto.setText("El Contacto ingresado ya fue registrado");
                }
                System.out.println(e.getMessage());
            }
        }
        
        else{
            imprimirErrores(apoderado.getErrores());
        }
    }
    
    private void actualizar(Apoderado apoderado){
        ApoderadoBO apoBO = new ApoderadoBO();
        
        if(apoderado.getErrores().isEmpty()){
            try {
                apoBO.actualizarApoderado(apoderado);
                dispose();
            } catch (Exception e) {
                if ( e.getMessage().contains("El DNI ingresado ya existe") ) {
                    jLabelDni.setText("El DNI ingresado ya fue registrado");
                }
                if ( e.getMessage().contains("El Contacto ingresado ya existe") ) {
                    jLabelContacto.setText("El Contacto ingresado ya fue registrado");
                }
                System.out.println(e.getMessage());
            }
        }
        
        else{
            imprimirErrores(apoderado.getErrores());
        }
    }
    
    private void imprimirErrores(Map<String, String> errores){    
        for (String error : errores.keySet().toArray(new String[0])) {
            switch (error) {
                case "contacto" -> jLabelContacto.setText(errores.get(error));
                case "apellido_paterno" -> jLabelApellidoPaterno.setText(errores.get(error));
                case "apellido_materno" -> jLabelApellidoMaterno.setText(errores.get(error));
                case "dni" -> jLabelDni.setText(errores.get(error));
                case "nombres" -> jLabelNombres.setText(errores.get(error));
            }
            System.out.println(error);
        }
    }
    
    private void limpiarErrores(){
        jLabelContacto.setText("-");
        jLabelApellidoPaterno.setText("-");
        jLabelApellidoMaterno.setText("-");
        jLabelDni.setText("-");
        jLabelNombres.setText("-");
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaApoderado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaApoderado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaApoderado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaApoderado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaApoderado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelApellidoMaterno;
    private javax.swing.JLabel jLabelApellidoPaterno;
    private javax.swing.JLabel jLabelContacto;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelNombres;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextApellidoMaterno;
    private javax.swing.JTextField jTextApellidoPaterno;
    private javax.swing.JTextField jTextContacto;
    private javax.swing.JTextField jTextDni;
    private javax.swing.JTextField jTextNombres;
    private javax.swing.JButton jbPrincipal;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlTitulo;
    // End of variables declaration//GEN-END:variables
}
