/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import BusinessLayer.AlumnoBO;
import BusinessLayer.PagoMatriculaBO;
import BusinessLayer.PagoPensionBO;
import BusinessLayer.PagoVariosBO;
import JavaBean.Alumno;
import JavaBean.Matricula;
import JavaBean.pagoMatricula;
import JavaBean.pagoPensiones;
import JavaBean.pagoVarios;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author black
 */
public class VentanaPagos extends javax.swing.JFrame {

    /**
     * Creates new form InsertPagos
     * @param tipoPago
     */
    private String tipoPago = "";
    
    public VentanaPagos(String tipoPago, pagoMatricula pagoMat) {    
        initComponents();
        
        jlTitulo.setText("Actualizar Pago Matricula");
        
        jlID.setText(String.valueOf(pagoMat.getPago_matricula_id()));
        jbPrincipal.setText("Actualizar");
        
        //Rellenar formulario
        jTextAlumnoId.setText( String.valueOf(pagoMat.getAlumno_id()) );
        jTextFecha.setText( pagoMat.getFecha().toString() );
        jTextMonto.setText( String.valueOf(pagoMat.getMonto()) );
        jTextObservacion.setText( pagoMat.getObservacion() );
        
        this.tipoPago = tipoPago;
        
//        try {
//            Alumno alumno = alumBO.buscarPorId(pagoMat.getPago_matricula_id());
//            JTextAlumnoNombrePagoInsertar.setText(alumno.getApellido_paterno()+" "+alumno.getApellido_materno()+" , "+alumno.getNombres());
//        } catch (Exception e) {
//            System.out.println(e.getMessage());
//        }
    }
    
    public VentanaPagos(String tipoPago, pagoPensiones pagoPen) {    
        initComponents();
        
        jlTitulo.setText("Actualizar Pago Pensiones");
        
        jlID.setText(String.valueOf(pagoPen.getPago_pensiones_id()));
        jbPrincipal.setText("Actualizar");
        
        //Rellenar formulario
        jTextAlumnoId.setText( String.valueOf(pagoPen.getAlumno_id()) );
        jTextFecha.setText( pagoPen.getFecha().toString() );
        jTextMonto.setText( String.valueOf(pagoPen.getMonto()) );
        jTextObservacion.setText( pagoPen.getObservacion() );
        
        this.tipoPago = tipoPago;
    }
    
    public VentanaPagos(String tipoPago, pagoVarios pagoVar) {    
        initComponents();
        
        jlTitulo.setText("Actualizar Pago Varios");
        
        jlID.setText(String.valueOf(pagoVar.getPago_varios_id()));
        jbPrincipal.setText("Actualizar");
        
        //Rellenar formulario
        jTextAlumnoId.setText( String.valueOf(pagoVar.getAlumno_id()) );
        jTextFecha.setText( pagoVar.getFecha().toString() );
        jTextMonto.setText( String.valueOf(pagoVar.getMonto()) );
        jTextObservacion.setText( pagoVar.getObservacion() );
        
        this.tipoPago = tipoPago;
    }
    
    
    public VentanaPagos(String tipoPago) {    
        initComponents();
        
        jlTitulo.setText("Insertar "+tipoPago);
        if(tipoPago.trim()=="Pago Varios")
            jLabel10.setText("Descripcion :");
        
        jlID.setText("");
        jbPrincipal.setText("Insertar");
        
        this.tipoPago = tipoPago;
        jbPrincipal.setEnabled(false);
        
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Insertar Pago"));
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        JTextAlumnoNombrePagoInsertar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jbPrincipal = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextFecha = new javax.swing.JTextField();
        jLabelFecha = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextMonto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabelMonto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextObservacion = new javax.swing.JTextArea();
        jLabelObservacion = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JTextBuscarNombre = new javax.swing.JTextField();
        btnBuscarAlumno = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();
        jTextAlumnoId = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabelAlumno_id = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();
        jlID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Actualizar Pago"));
        jPanel3.setToolTipText("");
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setMaximumSize(new java.awt.Dimension(275, 680));
        jPanel3.setMinimumSize(new java.awt.Dimension(275, 680));
        jPanel3.setName(""); // NOI18N

        JTextAlumnoNombrePagoInsertar.setEnabled(false);
        JTextAlumnoNombrePagoInsertar.setMaximumSize(new java.awt.Dimension(250, 22));
        JTextAlumnoNombrePagoInsertar.setMinimumSize(new java.awt.Dimension(250, 22));
        JTextAlumnoNombrePagoInsertar.setName(""); // NOI18N
        JTextAlumnoNombrePagoInsertar.setPreferredSize(new java.awt.Dimension(250, 22));

        jLabel1.setText("Alumno:");

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbPrincipal.setText("Registrar pago");
        jbPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrincipalActionPerformed(evt);
            }
        });

        jLabel16.setText("Fecha de pago :");

        jLabelFecha.setForeground(new java.awt.Color(255, 51, 51));
        jLabelFecha.setText("-");

        jLabel17.setText("Monto pagado :");

        jLabel10.setText("Observaciones :");

        jLabelMonto.setForeground(new java.awt.Color(255, 51, 51));
        jLabelMonto.setText("-");

        jTextObservacion.setColumns(20);
        jTextObservacion.setRows(5);
        jScrollPane1.setViewportView(jTextObservacion);

        jLabelObservacion.setForeground(new java.awt.Color(255, 51, 51));
        jLabelObservacion.setText("-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTextAlumnoNombrePagoInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelObservacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelMonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFecha))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextMonto))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jbPrincipal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTextAlumnoNombrePagoInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMonto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelObservacion)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPrincipal)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));

        jLabel2.setText("Nombres:");

        btnBuscarAlumno.setText("Buscar");
        btnBuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTextBuscarNombre)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscarAlumno)
                .addGap(96, 96, 96))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTextBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarAlumno))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccionar Alumno"));

        tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alumno id", "Apellidos y Nombres", "DNI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlumnosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAlumnos);

        jTextAlumnoId.setEnabled(false);

        jLabel19.setText("Alumno ID :");

        jLabelAlumno_id.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAlumno_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jTextAlumnoId)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextAlumnoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAlumno_id, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jlTitulo.setText("Actualizar Pago: ");

        jlID.setForeground(new java.awt.Color(51, 51, 255));
        jlID.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jlTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTitulo)
                    .addComponent(jlID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.getAccessibleContext().setAccessibleName("Insertar Pagos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrincipalActionPerformed
        // TODO add your handling code here:
        LimpiarErrores();
        
        switch (tipoPago) {
            case "Pago Matricula" -> {
                pagoMatricula pagoMat = RecibirDatosMatricula();
                InsertActualizar(pagoMat);
            }
            case "Pago Pensiones" -> {
                pagoPensiones pagoPen = RecibirDatosPensiones();
                InsertActualizar(pagoPen);
            }
            case "Pago Varios" -> {
                pagoVarios pagoVar = RecibirDatosVarios();
                InsertActualizar(pagoVar);
                }
        }
    }//GEN-LAST:event_jbPrincipalActionPerformed

    private pagoMatricula RecibirDatosMatricula(){
        pagoMatricula pagoMatricula1 = new pagoMatricula();
        
        int id = 0;
        double monto = 0;
        
        try {
            id = Integer.parseInt(jTextAlumnoId.getText());
        } catch (Exception e) {
            System.out.println(e.getMessage());
            jLabelAlumno_id.setText("Ingresa un número en el campo código alumno");
        }
        
        try {
            monto = Double.parseDouble(jTextMonto.getText() );
        } catch (Exception e) {
            System.out.println(e.getMessage());
            jLabelMonto.setText("Ingresa un número en el campo monto");
        }
        
        try {
            if(!jTextFecha.getText().isEmpty())
                pagoMatricula1.setFecha(Date.valueOf(jTextFecha.getText()).toLocalDate());
            else
                pagoMatricula1.setFecha(null);
        } catch (Exception e) {
            if(e.toString().equals("java.lang.IllegalArgumentException"))
                jLabelFecha.setText("Error en el formato de la Fecha de Nacimiento");
            
            System.out.println("Error: "+e.toString());
        }
        
        pagoMatricula1.setAlumno_id(id);
        pagoMatricula1.setMonto(monto);
        pagoMatricula1.setObservacion(jTextObservacion.getText());
        
        if(!jlID.getText().isEmpty())
            pagoMatricula1.setPago_matricula_id(Integer.parseInt(jlID.getText()));
        
        return pagoMatricula1;
    }
    
    private pagoPensiones RecibirDatosPensiones(){
        pagoPensiones pagoPensiones1= new pagoPensiones();
        
        int id = 0;
        double monto = 0;
        
        try {
            id = Integer.parseInt(jTextAlumnoId.getText());
        } catch (Exception e) {
            System.out.println(e.getMessage());
            jLabelAlumno_id.setText("Ingresa un número en el campo código alumno");
        }
        
        try {
            monto = Double.parseDouble(jTextMonto.getText() );
        } catch (Exception e) {
            System.out.println(e.getMessage());
            jLabelMonto.setText("Ingresa un número en el campo monto");
        }
        
        try {
            if(!jTextFecha.getText().isEmpty())
                pagoPensiones1.setFecha(Date.valueOf(jTextFecha.getText()).toLocalDate());
            else
                pagoPensiones1.setFecha(null);
        } catch (Exception e) {
            if(e.toString().equals("java.lang.IllegalArgumentException"))
                jLabelFecha.setText("Error en el formato de la Fecha de Nacimiento");
            
            System.out.println("Error: "+e.toString());
        }
        
        pagoPensiones1.setAlumno_id(id);
        pagoPensiones1.setMonto(monto);
        pagoPensiones1.setObservacion(jTextObservacion.getText());
        
        if(!jlID.getText().isEmpty())
            pagoPensiones1.setPago_pensiones_id(Integer.parseInt(jlID.getText()));
        
        return pagoPensiones1;
    }
    
    private pagoVarios RecibirDatosVarios(){
        pagoVarios pagoVarios1= new pagoVarios();
        
        int id = 0;
        double monto = 0;
        
        try {
            id = Integer.parseInt(jTextAlumnoId.getText());
        } catch (Exception e) {
            System.out.println(e.getMessage());
            jLabelAlumno_id.setText("Ingresa un número en el campo código alumno");
        }
        
        try {
            monto = Double.parseDouble(jTextMonto.getText() );
        } catch (Exception e) {
            System.out.println(e.getMessage());
            jLabelMonto.setText("Ingresa un número en el campo monto");
        }
        
        try {
            if(!jTextFecha.getText().isEmpty())
                pagoVarios1.setFecha(Date.valueOf(jTextFecha.getText()).toLocalDate());
            else
                pagoVarios1.setFecha(null);
        } catch (Exception e) {
            if(e.toString().equals("java.lang.IllegalArgumentException"))
                jLabelFecha.setText("Error en el formato de la Fecha de Nacimiento");
            
            System.out.println("Error: "+e.toString());
        }
        
        pagoVarios1.setAlumno_id(id);
        pagoVarios1.setMonto(monto);
        pagoVarios1.setObservacion(jTextObservacion.getText());
        
        if(!jlID.getText().isEmpty())
            pagoVarios1.setPago_varios_id(Integer.parseInt(jlID.getText()));
        
        return pagoVarios1;
    }
    
    private void InsertActualizar(pagoMatricula pagoMat){
        PagoMatriculaBO pagoMatBO = new PagoMatriculaBO();
        
        if(pagoMat.getErrores().isEmpty()){
            try {
                if (jbPrincipal.getText().equals("Insertar")) {
                    pagoMatBO.insertarPagoMatricula(pagoMat);
                } else if (jbPrincipal.getText().equals("Actualizar")) {
                    pagoMatBO.actualizarPagoMatricula(pagoMat);
                }
                
                dispose();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        
        else{
            ImprimirErrores(pagoMat.getErrores());
        }
    }
    
    private void InsertActualizar(pagoPensiones pagoPen){
        PagoPensionBO pagoPenBO = new PagoPensionBO();

        if (pagoPen.getErrores().isEmpty()) {
            try {
                if (jbPrincipal.getText().equals("Insertar")) {
                    pagoPenBO.insertarPagoPension(pagoPen);
                } else if (jbPrincipal.getText().equals("Actualizar")) {
                    pagoPenBO.actualizarPagoPension(pagoPen);
                }
                
                dispose();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        } else {
            ImprimirErrores(pagoPen.getErrores());
        }
    }
    
    private void InsertActualizar(pagoVarios pagoVar){
        PagoVariosBO pagoVarBO = new PagoVariosBO();

        if (pagoVar.getErrores().isEmpty()) {
            try {
                if (jbPrincipal.getText().equals("Insertar")) {
                    pagoVarBO.insertarPagoVarios(pagoVar);
                } else if (jbPrincipal.getText().equals("Actualizar")) {
                    pagoVarBO.actualizarPagoVarios(pagoVar);
                }
                
                dispose();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        } else {
            ImprimirErrores(pagoVar.getErrores());
        }
    }
    
    private void ImprimirErrores(Map<String, String> errores){
        for (String error : errores.keySet().toArray(new String[0])) {
            switch (error) {
                case "alumno_id" -> jLabelAlumno_id.setText(errores.get(error));
                case "fecha" -> jLabelFecha.setText(errores.get(error));
                case "monto" -> jLabelMonto.setText(errores.get(error));
                case "observacion" -> jLabelObservacion.setText(errores.get(error));
                case "descripcion" -> jLabelObservacion.setText(errores.get(error));
            }
            System.out.println(error);
        }
    }
    
    private void LimpiarErrores(){
        jLabelAlumno_id.setText("");
        jLabelFecha.setText("-");
        jLabelMonto.setText("-");
        jLabelObservacion.setText("-");
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlumnosMouseClicked
        // TODO add your handling code here:
        int fila = tblAlumnos.getSelectedRow();
        
        if(fila !=-1){
            JTextAlumnoNombrePagoInsertar.setText((String) tblAlumnos.getValueAt(fila, 1));
            jTextAlumnoId.setText(tblAlumnos.getValueAt(fila, 0).toString());
            jbPrincipal.setEnabled(true);
        }
    }//GEN-LAST:event_tblAlumnosMouseClicked

    private void btnBuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoActionPerformed
        try {
            alumnos = alumBO.buscarPorAlumno(JTextBuscarNombre.getText());
            actualizarTablaAlumno();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarAlumnoActionPerformed

    private DefaultTableModel modeloAlumnos;
    private AlumnoBO alumBO = new AlumnoBO();
    private ArrayList<Alumno>  alumnos;
    
    private void actualizarTablaAlumno(){
        modeloAlumnos = new DefaultTableModel();
        
        tblAlumnos.setModel(modeloAlumnos);
        
        modeloAlumnos.addColumn("Alumno id");
        modeloAlumnos.addColumn("Apellidos y Nombres");
        modeloAlumnos.addColumn("DNI");
        
        try {
            System.out.println(alumnos.size());
            for (int i = 0; i < alumnos.size(); i++) {
                Alumno alumno = alumnos.get(i);
                String apellidosNombres = alumno.getApellido_paterno()+" "+alumno.getApellido_materno()+" , "+alumno.getNombres();
                
                System.out.println(alumno.getCorreo_electrico());
                Object [] fila = new Object[] { alumno.getAlumno_id(), apellidosNombres, alumno.getDni()};
                modeloAlumnos.addRow(fila);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPagos("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextAlumnoNombrePagoInsertar;
    private javax.swing.JTextField JTextBuscarNombre;
    private javax.swing.JButton btnBuscarAlumno;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAlumno_id;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelMonto;
    private javax.swing.JLabel jLabelObservacion;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextAlumnoId;
    private javax.swing.JTextField jTextFecha;
    private javax.swing.JTextField jTextMonto;
    private javax.swing.JTextArea jTextObservacion;
    private javax.swing.JButton jbPrincipal;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTable tblAlumnos;
    // End of variables declaration//GEN-END:variables
}
