/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import BusinessLayer.AlumnoApoderadoBO;
import BusinessLayer.ApoderadoBO;
import JavaBean.Apoderado;
import JavaBean.alumnoApoderado;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author black
 */
public class VentanaInsertarApoderadoAlumno extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInsertarApoderadoAlAlumno
     */
    private int alumno_id = -1;
    
    public VentanaInsertarApoderadoAlumno(int alumno_id, String apellidos_nombres) {
        initComponents();
        
        this.alumno_id = alumno_id;
        jLabelApellidosNombres.setText(apellidos_nombres);
        
        try {
            apoderados = apoBO.buscarApoderadoPorNombre("");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        actualizarTablaApoderado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTableApoderado = new javax.swing.JTable();
        jTextApoderadoId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        JTextApoderadoNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbPrincipal = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextParentesco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelApellidosNombres = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecciona un Apoderado\n"));

        jTableApoderado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Apoderado_id", "Apellidos y Nombres", "DNI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableApoderado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableApoderadoMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(jTableApoderado);

        jTextApoderadoId.setEnabled(false);
        jTextApoderadoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextApoderadoIdActionPerformed(evt);
            }
        });

        jLabel9.setText("CODIGO APODERADO :");

        JTextApoderadoNombre.setEnabled(false);
        JTextApoderadoNombre.setMaximumSize(new java.awt.Dimension(250, 22));
        JTextApoderadoNombre.setMinimumSize(new java.awt.Dimension(250, 22));
        JTextApoderadoNombre.setName(""); // NOI18N
        JTextApoderadoNombre.setPreferredSize(new java.awt.Dimension(250, 22));

        jLabel1.setText("APODERADO :");

        jbPrincipal.setText("Insertar");
        jbPrincipal.setEnabled(false);
        jbPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrincipalActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel7.setText("PARENTESCO :");

        jLabelError.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextApoderadoId))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTextApoderadoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextParentesco, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButtonCancelar)
                        .addGap(42, 42, 42)
                        .addComponent(jbPrincipal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextApoderadoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextApoderadoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPrincipal)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        jLabel2.setText("Insertar Apoderado al Alumno:");

        jLabelApellidosNombres.setForeground(new java.awt.Color(153, 51, 255));
        jLabelApellidosNombres.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelApellidosNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelApellidosNombres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableApoderadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableApoderadoMouseClicked
        // TODO add your handling code here:
        int fila = jTableApoderado.getSelectedRow();

        if(fila !=-1){
            JTextApoderadoNombre.setText((String) jTableApoderado.getValueAt(fila, 1));
            jTextApoderadoId.setText(jTableApoderado.getValueAt(fila, 0).toString());
            jbPrincipal.setEnabled(true);
        }
    }//GEN-LAST:event_jTableApoderadoMouseClicked

    private void jTextApoderadoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextApoderadoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextApoderadoIdActionPerformed

    private void jbPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrincipalActionPerformed
        // TODO add your handling code here:
        jLabelError.setText("-");

        alumnoApoderado alumApo = new alumnoApoderado();
        AlumnoApoderadoBO alumnoApoderadoBO = new AlumnoApoderadoBO();

        if (jTextParentesco.getText().isEmpty()) {
            jLabelError.setText("El campo parentesco no debe estar vacía");
            return;
        }

        alumApo.setParentesco(jTextParentesco.getText());
        alumApo.setAlumno_id(alumno_id);
        alumApo.setApoderado_id(Integer.parseInt(jTextApoderadoId.getText()));

        try {
            alumnoApoderadoBO.insertar(alumApo);
            
            dispose();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jbPrincipalActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private DefaultTableModel modeloApoderado;
    private ArrayList<Apoderado> apoderados;
    private ApoderadoBO apoBO = new ApoderadoBO();

    private void actualizarTablaApoderado() {
        modeloApoderado = new DefaultTableModel();

        jTableApoderado.setModel(modeloApoderado);

        modeloApoderado.addColumn("apoderado_id");
        modeloApoderado.addColumn("apellido_nombres");
        modeloApoderado.addColumn("dni");
        
        try {
            for (int i = 0; i < apoderados.size(); i++) {
                Apoderado apoderado = apoderados.get(i);
                String apellidosNombres = apoderado.getApellido_paterno() + " " + apoderado.getApellido_materno() + " , " + apoderado.getNombres();

                Object[] fila = new Object[]{apoderado.getApoderado_id(),apellidosNombres,
                apoderado.getDni()};
                modeloApoderado.addRow(fila);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInsertarApoderadoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInsertarApoderadoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInsertarApoderadoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInsertarApoderadoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInsertarApoderadoAlumno(-1,"").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextApoderadoNombre;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelApellidosNombres;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTableApoderado;
    private javax.swing.JTextField jTextApoderadoId;
    private javax.swing.JTextField jTextParentesco;
    private javax.swing.JButton jbPrincipal;
    // End of variables declaration//GEN-END:variables
}
