/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import BusinessLayer.AlumnoBO;
import BusinessLayer.MatriculaBO;
import JavaBean.Alumno;
import JavaBean.Matricula;
import java.sql.Date;
import java.util.Map;

/**
 *
 * @author black
 */
public class VentanaMatricula extends javax.swing.JFrame {
    /**
     * Creates new form InsertMatricula
     */
    public VentanaMatricula(Matricula matricula) {
        initComponents();
        jlTitulo.setText("Actualizar Matricula: ");
        jlID.setText(String.valueOf(matricula.getMatricula_id()));
        jbPrincipal.setText("Actualizar");
                
        //Se completa el formulario
        jTextFechaMatricula.setText(matricula.getFecha().toString());
        jTextAlumno_id.setText(String.valueOf(matricula.getAlumno_id()));
        jComboBoxGrado.setSelectedIndex(Character.getNumericValue(matricula.getGrado()));
        
        switch (matricula.getNivel()) {
            case 'I' -> jComboBoxNivel.setSelectedIndex(1);
            case 'P' -> jComboBoxNivel.setSelectedIndex(2);
            case 'S' -> jComboBoxNivel.setSelectedIndex(3);
        }
        
        switch (matricula.getTurno()) {
            case 'D' -> jComboBoxTurno.setSelectedIndex(1);
            case 'T' -> jComboBoxTurno.setSelectedIndex(2);
        }
    }
    
    public VentanaMatricula() {
        initComponents();
        jlTitulo.setText("Insertar Matricula");
        jlID.setText("");
        jbPrincipal.setText("Insertar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextAlumno_id = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextNombres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFechaMatricula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbPrincipal = new javax.swing.JButton();
        jComboBoxTurno = new javax.swing.JComboBox<>();
        jComboBoxNivel = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxGrado = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabelAlumno_id = new javax.swing.JLabel();
        jLabelFechaMatricula = new javax.swing.JLabel();
        jLabelNivel = new javax.swing.JLabel();
        jLabelGrado = new javax.swing.JLabel();
        jLabelTurno = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();
        jlID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAlumno_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAlumno_idActionPerformed(evt);
            }
        });

        btn_buscar.setText("BUSCAR");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        jLabel3.setText("APELLIDOS Y NOMBRES :");

        jTextNombres.setEditable(false);
        jTextNombres.setBackground(new java.awt.Color(224, 224, 224));
        jTextNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombresActionPerformed(evt);
            }
        });

        jLabel4.setText("FECHA DE MATRICULA:");

        jLabel5.setText("NIVEL:");

        jLabel6.setText("TURNO:");

        jbPrincipal.setText("Insertar");
        jbPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrincipalActionPerformed(evt);
            }
        });

        jComboBoxTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Tarde" }));
        jComboBoxTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTurnoActionPerformed(evt);
            }
        });

        jComboBoxNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inicial", "Primaria", "Secundaria" }));
        jComboBoxNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNivelActionPerformed(evt);
            }
        });

        jLabel8.setText("GRADO:");

        jComboBoxGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1er° GRADO", "2er° GRADO", "3er° GRADO", "4er° GRADO", "5er° GRADO", "6er° GRADO" }));
        jComboBoxGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGradoActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setText("CODIGO ALUMNO:");

        jLabelAlumno_id.setForeground(new java.awt.Color(255, 51, 51));
        jLabelAlumno_id.setText("-");

        jLabelFechaMatricula.setForeground(new java.awt.Color(255, 51, 51));
        jLabelFechaMatricula.setText("-");

        jLabelNivel.setForeground(new java.awt.Color(255, 51, 51));
        jLabelNivel.setText("-");

        jLabelGrado.setForeground(new java.awt.Color(255, 51, 51));
        jLabelGrado.setText("-");

        jLabelTurno.setForeground(new java.awt.Color(255, 51, 51));
        jLabelTurno.setText("-");

        jlTitulo.setText("Actualizar Matricula: ");

        jlID.setForeground(new java.awt.Color(51, 51, 255));
        jlID.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAlumno_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextAlumno_id, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_buscar)))
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFechaMatricula)
                                            .addComponent(jComboBoxNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelFechaMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelNivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBoxGrado, 0, 150, Short.MAX_VALUE)
                                            .addComponent(jLabelGrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBoxTurno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(jbPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTitulo)
                    .addComponent(jlID))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextAlumno_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAlumno_id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFechaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFechaMatricula)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNivel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabelGrado)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextAlumno_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAlumno_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAlumno_idActionPerformed

    private void jbPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrincipalActionPerformed
        // TODO add your handling code here:
        Matricula matricula = RecibirDatos();
        
        if(jbPrincipal.getText().equals("Insertar"))
            Insertar(matricula);
        
        else if(jbPrincipal.getText().equals("Actualizar"))
            Actualizar(matricula);
    }//GEN-LAST:event_jbPrincipalActionPerformed
    
    private Matricula RecibirDatos(){
        Matricula matricula = new Matricula();
        
//        if(!(jComboBoxNivel.getSelectedIndex() == 0))
//            matricula.setNivel(jComboBoxNivel.getSelectedItem().toString().charAt(0));
//        else
//            matricula.setNivel(' ');
//        
//        if(!(jComboBoxGrado.getSelectedIndex() == 0))
//            matricula.setGrado(jComboBoxGrado.getSelectedItem().toString().charAt(0));
//        else
//            matricula.setGrado(' ');
//        
//        if(!(jComboBoxTurno.getSelectedIndex() == 0))
//            matricula.setTurno(jComboBoxTurno.getSelectedItem().toString().charAt(0));
//        else 
//            matricula.setTurno(' ');
        matricula.setNivel(jComboBoxNivel.getSelectedItem().toString().charAt(0));
        matricula.setGrado(jComboBoxGrado.getSelectedItem().toString().charAt(0));
        matricula.setTurno(jComboBoxTurno.getSelectedItem().toString().charAt(0));


        LimpiarErrores();
        try {
            matricula.setAlumno_id(Integer.parseInt(jTextAlumno_id.getText()));
        } catch (Exception e) {
            System.out.println(e.getMessage());
            jLabelAlumno_id.setText("Ingresa un número en el campo código alumno");
        }
           
        try {
            if(!jTextFechaMatricula.getText().isEmpty())
                matricula.setFecha(Date.valueOf(jTextFechaMatricula.getText()).toLocalDate());
            else
                matricula.setFecha(null);
        } catch (Exception e) {
            if(e.toString().equals("java.lang.IllegalArgumentException"))
                jLabelFechaMatricula.setText("Error en el formato de la Fecha de Nacimiento");
            
            System.out.println("Error: "+e.toString());
        }
        
        if(!jlID.getText().isEmpty())
            matricula.setMatricula_id(Integer.parseInt(jlID.getText()));
        
        return matricula;
    }
    
    private void Insertar(Matricula matricula){
        MatriculaBO matBO = new MatriculaBO();
        
        if(matricula.getErrores().isEmpty()){
            try {
                matBO.insertarMatricula(matricula);
                dispose();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        
        else{
            ImprimirErrores(matricula.getErrores());
        }
    }
    
    private void Actualizar(Matricula matricula){
        MatriculaBO matBO = new MatriculaBO();
        
        if(matricula.getErrores().isEmpty()){
            try {
                matBO.actualizarMatricula(matricula);
                dispose();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        
        else{
            ImprimirErrores(matricula.getErrores());
        }
    }
    private void ImprimirErrores(Map<String, String> errores){    
        for (String error : errores.keySet().toArray(new String[0])) {
            switch (error) {
                case "alumno_id" -> jLabelAlumno_id.setText(errores.get(error));
                case "fecha" -> jLabelFechaMatricula.setText(errores.get(error));
                case "nivel" -> jLabelNivel.setText(errores.get(error));
                case "grado" -> jLabelGrado.setText(errores.get(error));
                case "turno" -> jLabelTurno.setText(errores.get(error));
            }
            System.out.println(error);
        }
    }
    
    private void LimpiarErrores(){
        jLabelAlumno_id.setText("-");
        jLabelFechaMatricula.setText("-");
        jLabelNivel.setText("-");
        jLabelGrado.setText("-");
        jLabelTurno.setText("-");
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBoxGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGradoActionPerformed

    private void jComboBoxNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNivelActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        AlumnoBO alumBO = new AlumnoBO();
        int id = -1;
        
        try {
            id = Integer.parseInt(jTextAlumno_id.getText());
        } catch (Exception e) {
            System.out.println(e.getMessage());
            jLabelAlumno_id.setText("Ingresa un número en el campo código alumno");
            return;
        }
        
        try {
            Alumno alumno = alumBO.buscarPorId(id);
            
            jTextNombres.setText(alumno.getApellidosNombres() );
            
            jLabelAlumno_id.setText("");
        } catch (Exception e) {
            //"Cannot invoke \"JavaBean.Alumno.getApellidosNombres()\" because \"alumno\" is null"
            System.out.println( e.getMessage() );
            jLabelAlumno_id.setText("Alumno no encontrado");
            jTextNombres.setText("");
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void jTextNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombresActionPerformed

    private void jComboBoxTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTurnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMatricula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxGrado;
    private javax.swing.JComboBox<String> jComboBoxNivel;
    private javax.swing.JComboBox<String> jComboBoxTurno;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAlumno_id;
    private javax.swing.JLabel jLabelFechaMatricula;
    private javax.swing.JLabel jLabelGrado;
    private javax.swing.JLabel jLabelNivel;
    private javax.swing.JLabel jLabelTurno;
    private javax.swing.JTextField jTextAlumno_id;
    private javax.swing.JTextField jTextFechaMatricula;
    private javax.swing.JTextField jTextNombres;
    private javax.swing.JButton jbPrincipal;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlTitulo;
    // End of variables declaration//GEN-END:variables
}
